//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPILPracticalTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int DCLink { get; set; }
        public string Account { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public decimal PriceHalf { get; set; }
        public string Init { get; set; }
        public string Contact_Person { get; set; }
        public string Physical1 { get; set; }
        public string Physical2 { get; set; }
        public string Physical3 { get; set; }
        public string Physical4 { get; set; }
        public string Physical5 { get; set; }
        public string PhysicalPC { get; set; }
        public string Addressee { get; set; }
        public string Post1 { get; set; }
        public string Post2 { get; set; }
        public string Post3 { get; set; }
        public string Post4 { get; set; }
        public string Post5 { get; set; }
        public string PostPC { get; set; }
        public string Delivered_To { get; set; }
        public string Telephone { get; set; }
        public string Telephone2 { get; set; }
        public string Fax1 { get; set; }
        public string Fax2 { get; set; }
        public Nullable<int> AccountTerms { get; set; }
        public bool CT { get; set; }
        public string Tax_Number { get; set; }
        public string Registration { get; set; }
        public Nullable<double> Credit_Limit { get; set; }
        public Nullable<int> RepID { get; set; }
        public Nullable<double> Interest_Rate { get; set; }
        public Nullable<double> Discount { get; set; }
        public bool On_Hold { get; set; }
        public Nullable<int> BFOpenType { get; set; }
        public string EMail { get; set; }
        public Nullable<int> BankLink { get; set; }
        public string BranchCode { get; set; }
        public string BankAccNum { get; set; }
        public string BankAccType { get; set; }
        public Nullable<double> AutoDisc { get; set; }
        public Nullable<int> DiscMtrxRow { get; set; }
        public Nullable<int> MainAccLink { get; set; }
        public bool CashDebtor { get; set; }
        public Nullable<double> DCBalance { get; set; }
        public bool CheckTerms { get; set; }
        public bool UseEmail { get; set; }
        public Nullable<int> iIncidentTypeID { get; set; }
        public Nullable<int> iBusTypeID { get; set; }
        public Nullable<int> iBusClassID { get; set; }
        public Nullable<int> iCountryID { get; set; }
        public Nullable<int> iAgentID { get; set; }
        public Nullable<System.DateTime> dTimeStamp { get; set; }
        public string cAccDescription { get; set; }
        public string cWebPage { get; set; }
        public Nullable<int> iClassID { get; set; }
        public Nullable<int> iAreasID { get; set; }
        public string cBankRefNr { get; set; }
        public Nullable<int> iCurrencyID { get; set; }
        public bool bStatPrint { get; set; }
        public bool bStatEmail { get; set; }
        public string cStatEmailPass { get; set; }
        public bool bForCurAcc { get; set; }
        public Nullable<double> fForeignBalance { get; set; }
        public bool bTaxPrompt { get; set; }
        public Nullable<int> iARPriceListNameID { get; set; }
        public int iSettlementTermsID { get; set; }
        public bool bSourceDocPrint { get; set; }
        public bool bSourceDocEmail { get; set; }
        public int iEUCountryID { get; set; }
        public int iDefTaxTypeID { get; set; }
        public bool bCODAccount { get; set; }
        public Nullable<System.DateTime> udARDate { get; set; }
        public Nullable<int> uiARDeliveryMethod { get; set; }
        public string tOrderNotes { get; set; }
        public Nullable<int> uiARCATID { get; set; }
        public decimal FuelLevyPercen { get; set; }
        public int FLID { get; set; }
        public int AccountStatusID { get; set; }
        public double IGUFabRate { get; set; }
        public double CreditPercentage { get; set; }
        public double TotalDebitBalance { get; set; }
        public double TotInvoiced { get; set; }
        public double TotPending { get; set; }
        public double TotReceived { get; set; }
        public bool IsGlobalAcc { get; set; }
        public bool IsProspect { get; set; }
        public string CardIdentification { get; set; }
        public string LegalName { get; set; }
        public string TrustName { get; set; }
        public Nullable<System.DateTime> BusinessEstablished { get; set; }
        public string RegistrationNo { get; set; }
        public string ACN { get; set; }
        public string Token { get; set; }
        public int EntityStructureID { get; set; }
        public int InsuredID { get; set; }
        public Nullable<System.DateTime> CreditApplicationDate { get; set; }
        public Nullable<System.DateTime> PPS_ExpiryDate { get; set; }
        public string PersonalGurantee { get; set; }
        public string CC_NameOnCard { get; set; }
        public string CC_CardNumber { get; set; }
        public Nullable<System.DateTime> CC_ExpiryDate { get; set; }
        public string BSB { get; set; }
        public string AcountNumber { get; set; }
        public string AcountName { get; set; }
        public Nullable<System.DateTime> CreditSearch { get; set; }
        public string GONI { get; set; }
        public bool bSendOrderConfirmations { get; set; }
        public string EmailOrderConfirmationTo { get; set; }
        public string EmailTaxInvoicesTo { get; set; }
        public string EmailStatementsTo { get; set; }
        public int RebateID { get; set; }
        public string XeroGUID { get; set; }
    }
}
