//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPILPracticalTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientDetail
    {
        public int Id { get; set; }
        public Nullable<int> ClientId { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string RefNo { get; set; }
        public string Note { get; set; }
        public Nullable<decimal> TotalExclAmount { get; set; }
        public Nullable<decimal> TotalTaxAmount { get; set; }
        public Nullable<decimal> TotalInclAmount { get; set; }
    }
}
