//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPILPracticalTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalseDetail
    {
        public int Id { get; set; }
        public Nullable<int> StkItemId { get; set; }
        public string Note1 { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> tax { get; set; }
        public Nullable<decimal> ExclAmount { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<decimal> InclAmount { get; set; }
        public Nullable<int> ClientDetailId { get; set; }
    }
}
